services:
  api:
    container_name: nest_api
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_DB_URL: mongodb+srv://anenemaidohemmanuel:Johnpaul2@nodeexpressproject.em3im7i.mongodb.net/data-manager?retryWrites=true&w=majority

    volumes:
      - .:/usr/src/app
    command: npm run start
